from typing import Any, Protocol


class DatabaseConnection(Protocol):
    """Protocol for database connection operations"""

    async def fetch(self, query: str, *args) -> list[Any]: ...
    async def fetchrow(self, query: str, *args) -> Any: ...
    async def fetchval(self, query: str, *args) -> Any: ...
    async def execute(self, query: str, *args) -> str: ...
